# Fuzzby 进化中的参数
PARAMS = {
    'OPEN_SPACE_WEIGHT': 0.6,
    'CORNER_BONUS': 3.0,
    'EGG_BONUS': 1.5,
    'PARITY_BONUS': 0.4,
    'CENTER_BONUS': 0.2,
    'TRAP_PENALTY': 200.0,
    'ENEMY_TURD_PENALTY': 1.0,
    'VISIT_PENALTY': 3.512,
    'CHASE_WEIGHT': 0.2,
    'TURD_OFFENSE_BONUS': 3.0,
    'TURD_BLOCK_BONUS': 4.0,
}
